name: "Azure Resource Deployment"

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    terraform:
        runs-on: ubuntu-latest
        env:
            TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
            TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET}}
            TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
            TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: latest
            
            - name: login to azure
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: tf initialize
              run: terraform init

            - name: tf plan
              run: terraform plan

            - name: tf apply
              run: terraform apply -auto-approve

            - run: echo "Created resources"